# HTTP Server Configuration
quarkus.http.port=8081

# MySQL Database Configuration
quarkus.datasource.db-kind=mysql
quarkus.datasource.username=root
quarkus.datasource.password=your_password
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/Baza

# Hibernate Configuration
quarkus.hibernate-orm.database.generation=validate
# Use `update` if you want Quarkus to manage schema updates. However, setting this to `validate` ensures Quarkus validates the schema instead of trying to modify it, preventing the duplicate foreign key issue.
quarkus.hibernate-orm.sql-load-script=no-file

# Enable Swagger UI
quarkus.swagger-ui.always-include=true

# OpenAPI endpoint path
quarkus.smallrye-openapi.path=/openapi

# Swagger UI endpoint path
quarkus.swagger-ui.path=/swagger-ui
